fix: Tooltip appears unintended with `delayShow`
mohsinulhaq/react-popper-tooltip pull request #119
Opened 2021-02-19 07:17 UTC by czabaj

Clear the `showTooltip` timeout on `mouseleave`.
Also fix the potential memory leak with wrong `useEffect` call.
And improve Storybook story to allow simulate various `offset`.

fixes #117

2021-02-19 07:20 UTC, czabaj commented on src/usePopperTooltip.ts
> +  React.useEffect(() => stopTimer, [stopTimer]);
Create `stopTimer` callback to ease event handler register/unregister.

The `useEffect` was moved from the bottom, I believe it shall clear the timeout on _unmount_ to prevent memory leak, but it was written

```JavaScript
React.useEffect(() => clearTimeout(timer.current), []);
```

Which clears the timeout _onMount_ only.

Am I right?

2021-02-19 07:27 UTC, czabaj commented on src/usePopperTooltip.ts
> +      }
Until visible, the `mouseleave` stops the timer.

2021-02-19 07:28 UTC, czabaj commented on stories/basic.stories.tsx
> +  },
Added control to test various offsets.

2021-02-19 07:41 UTC, czabaj commented on stories/basic.stories.tsx
> +  offsetDistance = 6,
I suppressed this complaint. The `Example` component has no `propTypes` so I believe it is cleaner without it.

2021-02-19 08:05 UTC, czabaj commented
@mohsinulhaq just a side note. I think the logic could be simplified if we introduce another state for the `visible` state that is set even not yet applied (because of the delays). Something like

```
const [visible, setVisible] = useState(initialVisible)
const [visibleSync, setVisibleSync] = useState(initialVisible)
// single useEffect handles all the asynchrony
useEffect(() => {
  timer.current = window.setTimeout(
    () => setVisible(visibleSync),
    visibleSync ? finalConfig.delayShow : finalConfig.delayHide)
  )
  return () => window.clearTimeout(timer.current)
}, [visibleSync])
```

and then the `mousemove` handler can also be simplified. It now must remember such a `visibleSync` with local variable `lastMouseOutside`, but the `mousemove` could simply unregistered once the `visibleSync` is `false` and register when `visibleSync` is `true` which will fix all problems originating from reliance on `visible` state, which can be daleyed.

This is but more complicated refactoring and I would like to discuss it here (or somewhere else) for a later attempt to implement it. It could have many problems which I don't see just now.

2021-02-19 16:19 UTC, mohsinulhaq requested changes

2021-02-19 16:19 UTC, mohsinulhaq commented on stories/basic.stories.tsx
> +  offsetDistance = 6,
you would need to do this to avoid it

```ts
type ExampleProps = Config & { offsetDistance?: number }

export const Example: Story<ExampleProps> = ({...}: ExampleProps) => {
```

also, you should move the default offsetDistance value from here to bottom config
see the comment below

2021-02-19 16:19 UTC, mohsinulhaq commented on stories/basic.stories.tsx
> +  offsetDistance: {
add `defaultValue: 6` here

2021-02-19 16:19 UTC, mohsinulhaq commented on src/usePopperTooltip.ts
> +  React.useEffect(() => stopTimer, [stopTimer]);
not sure what was why it was done on mount, @denisborovikov was this intentional?

2021-02-19 16:19 UTC, mohsinulhaq commented on src/usePopperTooltip.ts
> +  const stopTimer = React.useCallback(() => clearTimeout(timer.current), []);
I dont think this is required, since its not passed to any component for it to change reference
just clearTimeout(timer.current) all over the place

2021-02-20 08:44 UTC, czabaj commented on src/usePopperTooltip.ts
> +  React.useEffect(() => stopTimer, [stopTimer]);
Checked again. The `timer` is used only in `{hide,show}Tooltip` callbacks. These are not called initially but on events. There is no need to clear the timeout on _mount_, but if some component sets the timeout, which performs `setState` or whatever, it _must_, as a rule of thumb, clear the timeout on `unMount` which you do by return a cleanup function from the `useEffect`.

It is very common to forget to wrap it in one more function, it was 

```JavaScript
React.useEffect(() => clearTimeout(timer.current), []);
```

but shall be 

```JavaScript
React.useEffect(() => () => clearTimeout(timer.current), []);
```

which is equivalent to

```JavaScript
React.useEffect(() => stopTimer, []);
```

2021-02-20 08:45 UTC, czabaj commented on stories/basic.stories.tsx
> +  offsetDistance = 6,
Nope. I managed to satisfy TypeScript compiler, this is an ESLint error. Like, really.

2021-02-20 08:53 UTC, mohsinulhaq commented on stories/basic.stories.tsx
> +  offsetDistance = 6,
I actually tried it. It does fix the ESlint error. Can you try it out?

2021-02-20 08:57 UTC, czabaj commented on stories/basic.stories.tsx
> +  offsetDistance = 6,
Does not work on my machine 😕 I even restarted the IDE to assure, that ESLint does not cache the error.
<img width="676" alt="Screenshot 2021-02-20 at 9 55 15" src="https://user-images.githubusercontent.com/47554112/108590097-056dc000-7362-11eb-8c3b-6a3461b5b748.png">

2021-02-20 09:02 UTC, czabaj commented on src/usePopperTooltip.ts
> +  const stopTimer = React.useCallback(() => clearTimeout(timer.current), []);
I pass the handler to `triggerRef.addEventListener('mouseleave', stopTimer);` and I though it will be convenient to have single reference of the function to simplify `removeEventListener` but actually, this ha a bug, as `useCallback` (as well as `useMemo`) does not guarantee the single reference will ever be created. It is just performance hint and the reference can be removed by GC (sounds like React uses WekMaps for this under the hood). I will inline the logic to places, where needed.

2021-02-20 09:23 UTC, mohsinulhaq commented on stories/basic.stories.tsx
> +  offsetDistance = 6,
@czabaj you haven't applied the ExampleProps to the component props :)

2021-02-20 09:37 UTC, mohsinulhaq commented on src/usePopperTooltip.ts
> +  const stopTimer = React.useCallback(() => clearTimeout(timer.current), []);
oh yes, i missed that you used it for removing the listener
although now it looks a bit uglier
instead of stopTimer being either a boolean or a function, can you just create the function directly and use the isvisible check to add/remove stopTimer, preferably with an if statement, instead of a conditional

2021-02-21 08:30 UTC, czabaj commented on src/usePopperTooltip.ts
> +  const stopTimer = React.useCallback(() => clearTimeout(timer.current), []);
I agree that hacking short circuits for "if statement" is ugly. But if you propose to attach the function always and test the `isVisible` inside it, I would rather not. It is better to not attach the function when the condition falses and there is a problem with function reference, that I must keep, to be able to unregister the listener later. I can rewrite this to if statement, but the `boolean | function` variable type does more good than harm IMHO.

2021-02-21 18:31 UTC, denisborovikov commented on src/usePopperTooltip.ts
> +  const stopTimer = React.useCallback(() => clearTimeout(timer.current), []);
@mohsinulhaq I don't remember I had an intention to clear the timer on mount, pretty sure it should be on unmount to avoid any related state changes when the component already unmounted.

2021-02-21 20:51 UTC, mohsinulhaq commented on src/usePopperTooltip.ts
>      };
```suggestion
    let stopTimer: any;
    if (!visible) {
      stopTimer = () => clearTimeout(timer.current);
      triggerRef.addEventListener('mouseleave', stopTimer);
    }
    return () => {
      triggerRef.removeEventListener('mouseenter', showTooltip);
      triggerRef.removeEventListener('mouseleave', stopTimer);
    };
```
how about this?

2021-02-22 09:21 UTC, czabaj commented on src/usePopperTooltip.ts
>      };
Rewrote to if statement 😒

2021-02-22 09:24 UTC, mohsinulhaq commented on src/usePopperTooltip.ts
> +      if (stopTimer) {
this is not really needed, removeEventListener is a noop for undefined callback

2021-02-23 07:58 UTC, czabaj commented on src/usePopperTooltip.ts
> +      if (stopTimer) {
Yes, but you will make the TypeScript compiler very sad.

2021-02-23 09:19 UTC, mohsinulhaq commented on src/usePopperTooltip.ts
> +      if (stopTimer) {
oh yes, you're right, totally forgot about TS

2021-02-23 10:16 UTC, mohsinulhaq approved these changes

2021-02-23 10:19 UTC, mohsinulhaq commented
@czabaj regarding the alternate `visibleSync` implementation that you proposed, if you want you can take a stab at it and raise a PR, I would be more than happy to get that merged if it simplifies the flow in any way.

2021-02-23 10:20 UTC, merged